
apply plugin: 'java'
apply plugin: 'maven-publish'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 11
}

repositories {
    mavenCentral()
}

dependencies {
    
    implementation fileTree(include: ['*.jar'], dir: 'libs/compile')
    
    runtimeOnly fileTree(include: ['*.jar'], dir: 'libs/runtime')
    
    testImplementation fileTree(include: ['*.jar'], dir: 'libs/testCompile')
    
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}




String mavenArtifactId = name
String versionString = rootProject.version

group = rootProject.versionInfo.mavenGroupId
version = versionString

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = rootProject.versionInfo.mavenGroupId
            artifactId = mavenArtifactId
            version = versionString
        }
    }
}

tasks.register('createFolders') {
    description = 'Creates the source folders if they do not exist.'
    doLast {
    sourceSets*.allSource*.srcDirs*.each { File srcDir ->
        if (!srcDir.isDirectory()) {
            println "Creating source folder: ${srcDir}"
            srcDir.mkdirs()
        }
    }
    }
}

tasks.register('copyRuntimeLibs', Sync) {
    into layout.buildDirectory.dir('libs/lib')
    from configurations.runtimeClasspath
    doLast {
        logger.lifecycle("Runtime libraries copied to ${destinationDir}")
    }
}

tasks.named('jar') {
    dependsOn tasks.named('copyRuntimeLibs')

    manifest {
        attributes(
            'Main-Class': project.hasProperty('mainClass')? project.ext.mainClass:'',
            'SplashScreen-Image': project.hasProperty('splashScreen')? project.ext.splashScreen:'',
            'Class-Path': configurations.runtimeClasspath.collect { 'lib/' + it.getName() }.join(' '))
    }
}
