apply plugin: 'antlr'

dependencies {

    antlr "org.antlr:antlr4:4.13.2" // keep generator and runtime on the same version
    
    // https://mvnrepository.com/artifact/org.antlr/antlr4-runtime
    implementation group: 'org.antlr', name: 'antlr4-runtime', version: '4.13.2'

    
    // https://mvnrepository.com/artifact/org.apache.commons/commons-exec
    implementation group: 'org.apache.commons', name: 'commons-exec', version: '1.4.0'
    
    // https://mvnrepository.com/artifact/com.googlecode.soundlibs/jlayer
    runtimeOnly(group: 'com.googlecode.soundlibs', name: 'jlayer', version: '1.0.1-1') {
        exclude group: 'junit', module: 'junit'
    }
    
    // https://mvnrepository.com/artifact/com.googlecode.soundlibs/mp3spi
    runtimeOnly(group: 'com.googlecode.soundlibs', name: 'mp3spi', version: '1.9.5-1') {
        exclude group: 'junit', module: 'junit'
    }
    
    // https://mvnrepository.com/artifact/com.googlecode.soundlibs/tritonus-share
    runtimeOnly group: 'com.googlecode.soundlibs', name: 'tritonus-share', version: '0.3.7.4'
    
    // https://mvnrepository.com/artifact/org.apache.httpcomponents/fluent-hc
    implementation group: 'org.apache.httpcomponents', name: 'fluent-hc', version: '4.5.14'
       
    //https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.17.3'
    
    //https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.17.3'
    
    //https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-xml
    implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-xml', version: '2.17.3'
    
    // https://mvnrepository.com/artifact/org.json/json
    implementation group: 'org.json', name: 'json', version: '20250107'
    
    
    // Talvez possa ser substituído pela dependência abaixo
    // https://mvnrepository.com/artifact/javax.media/jmf
    //compile group: 'javax.media', name: 'jmf', version: 'fs-3.0'
}

generateGrammarSource {

    def classesPackage = "br.univali.portugol.nucleo.analise.sintatica.antlr4";
    def sourceDir = "src/main/java/" + classesPackage.replace('.', '/');

    outputDirectory = file(sourceDir)
    arguments += ["-visitor", "-no-listener", "-package", classesPackage.toString()]
}

tasks.named('sourcesJar') {
    dependsOn tasks.named('generateGrammarSource')
}
